# Generated by Django 2.2 on 2020-03-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(help_text='This field is mandatory', max_length=85)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
